export const SERVICE_ICONS = {
  airtime: require("../../../assets/icons/call-outgoing.png"),
  utility: require("../../../assets/icons/point-of-sale-bill.png"),
  data: require("../../../assets/icons/smartphone.png"),
  betting: require("../../../assets/icons/poker-chip.png"),
  tv: require("../../../assets/icons/tv-retro.png"),
  travel: require("../../../assets/icons/plane-alt.png"),
  internet: require("../../../assets/icons/globe-pointer.png"),
  other: require("../../../assets/icons/receipt.png"),
  requestLoan: require("../../../assets/icons/loan.png"),
  insurance: require("../../../assets/icons/umbrella.png"),
  schedule: require("../../../assets/icons/time-past.png"),
  basicSavings: require("../../../assets/icons/basic_savings.png"),
  targetSavings: require("../../../assets/icons/target.png"),
  groupSavings: require("../../../assets/icons/target_savings.png"),
  fixedDeposit: require("../../../assets/icons/group_savings.png"),
  shares: require("../../../assets/icons/shares.png"),
  gold: require("../../../assets/icons/buy_shares.png"),
};
